### ISSUE TITLE
Kagerou just break everytime someone else than me is parsed

### ISSUE THREAD

**Issue by Ytilee** [hibiyasleep/kagerou#54] opened 2017-07-16 20:24 UTC
It's always the exact same error written in the logs.
16/07/2017 22:18:57: Info: Kagerou: BrowserConsole: Uncaught ReferenceError: conf is not defined (Source: https://cdn.ravenjs.com/3.15.0/raven.min.js, Line: 2)
Act still works perfectly and any other configuration of mini parse still works too but kagerou just show a blank window
![capture](https://user-images.githubusercontent.com/1778770/28251047-7580155e-6a75-11e7-9f91-21c518bbed08.PNG)
I hope my informations can help

**Comment by Ytilee** [comment] 2017-07-16 20:33
I'm sorry, I just saw this was already covered by another issue : (this one : https://github.com/hibiyasleep/kagerou/issues/52)
I don't know how to close the issue myself. SOoo, sorry.

**Comment by hibiyasleep** [comment] 2017-07-16 23:32
it's fine, this was caused by my little typo and fixed on c423afee74535c6bffd7b1e52dc751767b2e8b99. sorry for inconvience ;(

**Closed by hibiyasleep** 2017-07-16 23:32 UTC
