### ISSUE TITLE
New error since last update

### ISSUE THREAD

**Issue by OnyxMemory** [hibiyasleep/kagerou#129] opened 2019-07-04 17:55 UTC
2019-07-04 11:41:19 AM: Info: Mini Parse: BrowserConsole: Uncaught TypeError: VALID_PLAYER_JOBS.includes is not a function (Source: https://cdn.ravenjs.com/3.17.0/raven.min.js, Line: 2)

Overlay doesnt seem to be rendering now.

**Comment by tempey** [comment] 2019-07-04 18:02
I am getting this error as well. FFXIV plugin updated and i'm assuming it broke it

**Comment by ffmstrife** [comment] 2019-07-04 18:10
Same issue on my end, standard mini-parse working properly.

**Comment by Fank** [comment] 2019-07-04 18:26
im using 0.7.26 and it looks fine with the parser version 2.0.2.3

**Comment by Tataru-Taru** [comment] 2019-07-04 18:33
Hmm not working for me and I'm using 0.7.26 adn 2.0.2.3 - ACT shows the DPS, but the overlay doesn't update.

**Comment by ffmstrife** [comment] 2019-07-04 18:34
> Hmm not working for me and I'm using 0.7.26 adn 2.0.2.3 - ACT shows the DPS, but the overlay doesn't update.
> 
> When it first starts the top moves down, but doesn't show all dps lines.

yea, same exactly, shows on ACT, moves a bit when combat starts but nothing shows

**Comment by MeatFeast** [comment] 2019-07-04 18:42
Having same problem as above, turning off 'pet merging' in the settings fixes it so I guess it's to do with that?

**Comment by Max16111** [comment] 2019-07-04 18:50
Same problem since after the update the overlay is not showing the dps nums but on ACT its working

**Comment by Max16111** [comment] 2019-07-04 18:53
> Having same problem as above, turning off 'pet merging' in the settings fixes it so I guess it's to do with that?

how do u do that?

**Comment by ffmstrife** [comment] 2019-07-04 18:53
> > Having same problem as above, turning off 'pet merging' in the settings fixes it so I guess it's to do with that?
> 
> how do u do that?

top right, three dots, click arrow there for pet merging, it fixes the issue, yep.

**Comment by Max16111** [comment] 2019-07-04 18:55
> > > Having same problem as above, turning off 'pet merging' in the settings fixes it so I guess it's to do with that?
> > 
> > 
> > how do u do that?
> 
> top right, three dots, click arrow there for pet merging, it fixes the issue, yep.

thx now working fine after i disabled it cheers

**Comment by Tataru-Taru** [comment] 2019-07-04 19:02
Thanks for that info.

**Comment by CyrexZ** [comment] 2019-07-04 19:41
> > > Having same problem as above, turning off 'pet merging' in the settings fixes it so I guess it's to do with that?
> > 
> > 
> > how do u do that?
> 
> top right, three dots, click arrow there for pet merging, it fixes the issue, yep.

I'm sorry I must be completely missing it. You mean on the actual overlay the three dots or settings? I see "Merge Pets" option there under general but I don't see any box or anything that I can use to disable it, theres just a box that lets me type in my name under it and deleting my name from there dosen't work. Also tried going to plugin and FFXIV settings in ACT and clicking on "disable merge with pets" which also didn't work.

**Comment by Tataru-Taru** [comment] 2019-07-04 19:41
https://i.imgur.com/PZOjkwf.png - there

**Comment by sisco1986** [comment] 2019-07-04 23:14
welp disabling the pet merging is not working for me

**Comment by hibiyasleep** [comment] 2019-07-05 02:06
This was caused by [this line](https://github.com/hibiyasleep/kagerou/commit/ef9b7ed07841ce24b79946671dba35455dd1e6cc#diff-3e5d95a6c5e88804006835d3e693ef3eR42) of commit - and I forgot that OverlayPlugin is running with very old chromium so `Array#includes` isn't present.

it was fixed by 94202f7decef7b3c309b410c591da7ba06d8954e - sorry for inconvenience, please try refresh overlay few times.

**Closed by hibiyasleep** 2019-07-05 02:06 UTC
